version: '3.3'
services:
  cnn:
    image: image-service-cnn
    restart: always
    volumes:
      - "image-volume:/images"
  denta:
    image: image-service-denta
    restart: always
    volumes:
      - "image-volume:/images"
    ports:
        - "80:80"
    environment:
      - ip=cnn
      - port=8888
      - image_dir=/images/
volumes:
  image-volume:
